# Generated by Django 3.2 on 2021-07-18 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'customuser', 'verbose_name_plural': 'customusers'},
        ),
    ]
